tidy version-check
mostly whitespace

diff --git a/shell/version-check b/shell/version-check
--- a/shell/version-check
+++ b/shell/version-check
@@ -4,21 +4,22 @@
 # Simple script to list version numbers of critical development tools
 
 if [ -e /usr/bin/arch ]; then
-  echo arch `arch`
+	echo arch `arch`
 fi
 echo "uname -m " `uname -m`
 
 echo MACHTYPE=${MACHTYPE}
 if [ -e /proc/cpuinfo ]; then
-  cat /proc/cpuinfo | grep 'system type' | head -n1 | cut -d":" -f2
-  cat /proc/cpuinfo | grep 'cpu model\|model name' | head -n1 | cut -d":" -f2
+	for WHAT in 'system type' 'cpu model\|model name'; do
+		cat /proc/cpuinfo | grep "$WHAT" | head -n1 | cut -d":" -f2
+	done
 else
-  echo "no /proc/cpuinfo"
+	echo "no /proc/cpuinfo"
 fi
 if [ -e /proc/version ]; then
-  cat /proc/version
+	cat /proc/version
 else
-  uname -a
+	uname -a
 fi
 echo ""
 
@@ -28,11 +29,11 @@ echo "/usr/bin/c++ -> `readlink -f /usr/bin/c++`"
 g++ --version | head -n1
 LIBC_SO=/lib/libc.so.6
 if [ -e /lib/libc/so.6 ]; then
-   LIBC_SO=/lib/libc/so.6
+	LIBC_SO=/lib/libc/so.6
 elif [ -e /lib/i386-linux-gnu/libc.so.6 ]; then
-   LIBC_SO=/lib/i386-linux-gnu/libc.so.6
+	LIBC_SO=/lib/i386-linux-gnu/libc.so.6
 elif [ -e /lib/x86_64-linux-gnu/libc.so.6 ]; then
-   LIBC_SO=/lib/x86_64-linux-gnu/libc.so.6
+	LIBC_SO=/lib/x86_64-linux-gnu/libc.so.6
 fi
 echo "$LIBC_SO : `$LIBC_SO | head -n1 | cut -d"," -f1`"
 
@@ -42,10 +43,10 @@ mkdir -p $DIR
 FILE="${DIR}/dummy"
 echo 'int main(void){return 0;}' > ${FILE}.c && gcc -o ${FILE} ${FILE}.c
 if [ -x ${FILE} ]; then
-  echo "gcc Compilation OK";
-  rm -f ${FILE}.c ${FILE}
+	echo "gcc Compilation OK";
+	rm -f ${FILE}.c ${FILE}
 else
-  echo "gcc -o ${FILE} ${FILE}.c failed";
+	echo "gcc -o ${FILE} ${FILE}.c failed";
 fi
 
 FILE="$DIR/hello"
@@ -61,49 +62,51 @@ gcc -o ${FILE} ${FILE}.c
 file ${FILE} | cut -d":" -f2
 readelf -l ${FILE} | grep ': /lib'
 if [ -x ${FILE} ]; then
-  HELLO=$(${FILE});
-  if [[ $HELLO = "hello, world." ]]
-  then
-    echo "execution OK";
-    rm -f ${FILE}.c ${FILE}
-  else
-    echo "gcc compiled ${FILE} execution failed";
-    echo "result was '$HELLO'";
-  fi
+	HELLO=$(${FILE});
+	if [[ $HELLO = "hello, world." ]]
+	then
+	echo "execution OK";
+	rm -f ${FILE}.c ${FILE}
+	else
+	echo "gcc compiled ${FILE} execution failed";
+	echo "result was '$HELLO'";
+	fi
 else
-    echo "gcc -o ${FILE} ${FILE}.c failed";
+	echo "gcc -o ${FILE} ${FILE}.c failed";
 fi
 echo ""
 
 echo "/bin/sh -> `readlink -f /bin/sh`"
 
 if [ -e /usr/bin/yacc ]; then
-  echo "/usr/bin/yacc -> `readlink -f /usr/bin/yacc`";
+	echo "/usr/bin/yacc -> `readlink -f /usr/bin/yacc`";
 else
-  echo "yacc not found";
+	echo "yacc not found";
 fi
 if [ -e /usr/bin/awk ]; then
-  echo "/usr/bin/awk -> `readlink -f /usr/bin/awk`";
+	echo "/usr/bin/awk -> `readlink -f /usr/bin/awk`";
 else
-  echo "awk not found";
+	echo "awk not found";
 fi
 echo -n "Coreutils: "; chown --version | head -n1 | cut -d")" -f2
 bzip2 --version 2>&1 < /dev/null | head -n1 | cut -d" " -f1,6-
 echo -n "libpng: "; /usr/bin/libpng-config --version || echo "(no libpng)"
-echo "mtdev: $(find /usr/lib /usr/local/lib /lib -name 'mtdev.pc' -exec grep Version \{} \; 2>/dev/null | sort -r | head -n1 || echo "(none)")"
+echo "mtdev: $(find /usr/lib /usr/local/lib /lib -name 'mtdev.pc' \
+		-exec grep Version \{} \; 2>/dev/null \
+		| sort -r | head -n1 || echo "(none)")"
 echo "Perl $(perl -V:version)" | sed 's/version=//g' | tr -d "';"
 echo "pkg-config: $(pkg-config --version 2>/dev/null)" ||
-     echo "(no pkg-config)" | head -n1
+	echo "(no pkg-config)" | head -n1
 grep "TALLOC_VERSION" \
-  $( find /usr/include /usr/local/include -name talloc.h ) \
-     /usr/include/stdio.h \
-  || echo "(no talloc)"
+	$( find /usr/include /usr/local/include -name talloc.h ) \
+		/usr/include/stdio.h \
+	|| echo "(no talloc)"
 echo "Texinfo: `makeinfo --version | head -n1`"
 echo "tic: `tic -V`"
 grep "define\s*ZLIB_VERSION\s" \
-   $(find /usr/include /usr/local/include -name zlib.h ) \
-     /usr/include/stdio.h \
-   || echo "(no zib)"
+	$(find /usr/include /usr/local/include -name zlib.h ) \
+		/usr/include/stdio.h \
+	|| echo "(no zib)"
 
 for CMD in \
 	as \
@@ -136,8 +139,8 @@ for CMD in \
 	xz \
 ; do
 	if command -v $CMD >/dev/null 2>&1; then
-		$CMD --version | head -n1
+	$CMD --version | head -n1
 	else
-		echo "(no $CMD)"
+	echo "(no $CMD)"
 	fi
 done
